#!/bin/bash
####################################<
### "BY ACKHTTP SERVER MANAGER >> @GODYSKYUP <<" ###
####################################<
user=$(whoami)
if [ "$user" != "root" ]; then
echo "DEVE SER EXECUTADO COMO ROOT! >> SUDO -I <<"
fi
#remontar os sistemas de arquivos com sinalizadores noatime e nodiratime
# se a montagem não for bem-sucedida, a montagem manual fará o melhor para você
mount -o remount,noatime,nodiratime,nobarrier auto /
mount -o remount,noatime,nodiratime, auto /dev
mount -o remount,noatime,nodiratime, auto /proc
mount -o remount,noatime,nodiratime, auto /sys
### INIT ROUTE
/sbin/ip route | while read p; do ip route change $p initcwnd 10 initrwnd 10 cwnd 10 mtu lock 9000 congctl lock illinois quickack 1; done
/sbin/ifconfig eth0 mtu 9000
/sbin/ifconfig eth0 txqueuelen 13888
/sbin/ifconfig ens5 mtu 9000
/sbin/ifconfig ens5 txqueuelen 13888
/sbin/ifconfig lo mtu 9000
/sbin/ifconfig lo txqueuelen 13888
ethtool -G eth0 rx 3502
ethtool -G eth0 tx 2048
ethtool -G ens5 rx 3502
ethtool -G ens5 tx 2048
bash -c 'echo 1 > /sys/module/processor/parameters/ignore_ppc'
bash -c 'echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource'
bash -c 'echo 4400000 > /scaling_max_freq'
echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo "obase=16;2^$(nproc)-1" | bc > /sys/class/net/eth0/queues/rx-0/rps_cpus
/sbin/iptables-restore < /etc/iptables.conf
#"1"
#### "VM" ###
echo 1048576 > /proc/sys/fs/nr_open
echo 1048576 > /proc/sys/fs/file-max
echo 200 > /proc/sys/vm/vfs_cache_pressure
echo 100 > /proc/sys/vm/swappiness
echo 16 > /proc/sys/vm/page-cluster
echo 1 > /proc/sys/vm/dirty_ratio
echo 1 > /proc/sys/vm/dirty_background_ratio
echo 1 > /proc/sys/vm/overcommit_memory
#"2"
#### "KERNEL" ###
echo 800000000 > /proc/sys/kernel/sched_migration_cost_ns
echo 1000000 > /proc/sys/kernel/sched_latency_ns
echo 32768 > /proc/sys/kernel/sched_nr_migrate
echo 10000 > /proc/sys/kernel/sched_wakeup_granularity_ns
echo 16384 > /proc/sys/kernel/threads-max
echo 16384 > /proc/sys/kernel/pid_max
echo 8192 > /proc/sys/kernel/pty/max
echo 1 > /proc/sys/kernel/sched_tunable_scaling
echo -1 > /proc/sys/kernel/sched_rt_runtime_us
echo -1 > /proc/sys/kernel/sched_rt_period_us
echo -1 >/proc/sys/kernel/sched_rr_timeslice_ms
echo 0 > /proc/sys/kernel/sched_autogroup_enabled
#"3"
### "BUFFER TCP ---" ###
echo 10000000 10000000 10000000 > /proc/sys/net/ipv4/tcp_mem
echo 10000000 10000000 10000000 > /proc/sys/net/ipv4/udp_mem
echo 4096 524288 11960320 > /proc/sys/net/ipv4/tcp_wmem
echo 4096 524288 11960320 > /proc/sys/net/ipv4/tcp_rmem
echo 11960320 > /proc/sys/net/core/rmem_default
echo 11960320 > /proc/sys/net/core/wmem_default
echo 11960320 > /proc/sys/net/core/wmem_max
echo 11960320 > /proc/sys/net/core/rmem_max
echo 16834 > /proc/sys/net/ipv4/udp_wmem_min
echo 16384 > /proc/sys/net/ipv4/udp_rmem_min
#"4"
### "NET.CORE EM GERAL" ###
echo 16384 > /proc/sys/net/core/optmem_max
echo 16384 > /proc/sys/net/core/somaxconn
echo 32768 > /proc/sys/net/core/netdev_max_backlog
echo 32768 > /proc/sys/net/core/flow_limit_table_len
echo 16384 > /proc/sys/net/unix/max_dgram_qlen
echo 16384 > /proc/sys/net/core/netdev_budget
echo 4096 > /proc/sys/net/core/rps_sock_flow_entries
echo 4096 > /sys/class/net/eth0/queues/rx-0/rps_flow_cnt
echo 1024 > /proc/sys/net/core/dev_weight
echo 25 > /proc/sys/net/core/busy_read
echo 25 > /proc/sys/net/core/busy_poll
#"5"
### "CONGESTIONAMENTO TCP/CORE" ###
echo illinois > /proc/sys/net/ipv4/tcp_congestion_control
echo illinois > /proc/sys/net/ipv4/tcp_allowed_congestion_control
echo fq > /proc/sys/net/core/default_qdisc
#"6"
### "TEMPO DE CONEXAO TCP" ###
echo 1800 > /proc/sys/net/ipv4/route/mtu_expires
echo 1024 > /proc/sys/net/ipv4/tcp_keepalive_probes
echo 1024 > /proc/sys/net/ipv4/tcp_synack_retries
echo 300 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 120 > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo 100 > /proc/sys/net/ipv4/tcp_syn_retries
echo 30 > /proc/sys/net/ipv4/tcp_probe_interval
echo 15 > /proc/sys/net/ipv4/tcp_fin_timeout
#"7"
### "TCP" ###
echo 60000 65535 > /proc/sys/net/ipv4/ip_local_port_range
echo 32768 > /proc/sys/net/ipv4/tcp_max_syn_backlog
echo 16384 > /proc/sys/net/ipv4/tcp_notsent_lowat
echo 16384 > /proc/sys/net/ipv4/tcp_max_tw_buckets
echo 1460 > /proc/sys/net/ipv4/tcp_base_mss
echo 8192 > /proc/sys/net/ipv4/tcp_max_orphans
echo 1024 > /proc/sys/net/ipv4/tcp_min_rtt_wlen
echo 1024 > /proc/sys/net/ipv4/tcp_reordering
echo 1024 > /proc/sys/net/ipv4/tcp_min_snd_mss
echo 1024 > /proc/sys/net/ipv4/tcp_min_tso_segs
echo 1024 > /proc/sys/net/ipv4/route/min_adv_mss
echo 1024 > /proc/sys/net/ipv4/tcp_probe_threshold
echo 1024 > /proc/sys/net/ipv4/tcp_fastopen
echo 900 > /proc/sys/net/ipv4/tcp_pacing_ca_ratio
echo 900 > /proc/sys/net/ipv4/tcp_pacing_ss_ratio
echo 600 > /proc/sys/net/ipv4/tcp_max_reordering
echo 8 > /proc/sys/net/ipv4/tcp_window_scaling
echo 8 > /proc/sys/net/ipv4/tcp_tso_win_divisor
echo 8 > /proc/sys/net/ipv4/tcp_adv_win_scale
echo 2 > /proc/sys/net/ipv4/tcp_mtu_probing
echo 2 > /proc/sys/net/ipv4/tcp_orphan_retries
echo 1 > /proc/sys/net/ipv4/tcp_abort_on_overflow
echo 1 > /proc/sys/net/ipv4/fwmark_reflect
echo 1 > /proc/sys/net/ipv4/ip_forward_use_pmtu
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/tcp_thin_linear_timeouts
echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
echo 1 > /proc/sys/net/ipv4/tcp_no_metrics_save
echo 1 > /proc/sys/net/ipv4/tcp_early_retrans
echo 1 > /proc/sys/net/ipv4/fib_multipath_use_neigh
echo 0 > /proc/sys/net/ipv4/ipfrag_time
echo 0 > /proc/sys/net/ipv4/xfrm4_gc_thresh
echo 0 > /proc/sys/net/ipv4/tcp_app_win
echo 0 > /proc/sys/net/ipv4/tcp_ecn_fallback
echo 0 > /proc/sys/net/ipv4/tcp_invalid_ratelimit
echo 0 > /proc/sys/net/ipv4/tcp_timestamps
echo 0 > /proc/sys/net/ipv4/tcp_moderate_rcvbuf
echo 0 > /proc/sys/net/ipv4/tcp_ecn
echo 0 > /proc/sys/net/ipv4/tcp_slow_start_after_idle
echo 0 > /proc/sys/net/ipv4/tcp_frto
#"8"
### "INTERFACE ROUTE" ###0
echo 32768 > /proc/sys/net/ipv4/route/max_size
echo 16384 > /proc/sys/net/ipv4/route/gc_thresh
echo 16384 > /proc/sys/net/ipv4/route/gc_elasticity
echo 120 > /proc/sys/net/ipv4/route/gc_interval
echo 15 > /proc/sys/net/ipv4/route/mtu_expires
echo 15 > /proc/sys/net/ipv4/route/gc_timeout
echo 1024 > /proc/sys/net/ipv4/route/min_adv_mss
echo 1024 > /proc/sys/net/ipv4/route/min_pmtu
### "INTERFACE DEFAULT" ###
echo 11960320 > /proc/sys/net/ipv4/neigh/default/unres_qlen_bytes
echo 32768 > /proc/sys/net/ipv4/neigh/default/unres_qlen
echo 16384 > /proc/sys/net/ipv4/neigh/default/proxy_qlen
echo 16384 > /proc/sys/net/ipv4/neigh/default/gc_thresh3
echo 8192 > /proc/sys/net/ipv4/neigh/default/gc_thresh2
echo 4096 > /proc/sys/net/ipv4/neigh/default/gc_thresh1
echo 300 > /proc/sys/net/ipv4/neigh/default/base_reachable_time
echo 300 > /proc/sys/net/ipv4/neigh/default/gc_stale_time
echo 120 > /proc/sys/net/ipv4/neigh/default/gc_interval
###"INTERFACE ETH0"###
echo 16777216 > /proc/sys/net/ipv4/neigh/eth0/proxy_qlen
echo 16777216 > /proc/sys/net/ipv4/neigh/eth0/unres_qlen_bytes
echo 86400 > /proc/sys/net/ipv4/neigh/eth0/gc_stale_time
echo 86400 > /proc/sys/net/ipv4/neigh/eth0/base_reachable_time
echo 32768 > /proc/sys/net/ipv4/neigh/eth0/unres_qlen
###"INTERFACE LO"###
echo 11960320 > /proc/sys/net/ipv4/neigh/lo/unres_qlen_bytes
echo 32768 > /proc/sys/net/ipv4/neigh/lo/unres_qlen
echo 16384 > /proc/sys/net/ipv4/neigh/lo/proxy_qlen
echo 300 > /proc/sys/net/ipv4/neigh/lo/gc_stale_time
echo 300 > /proc/sys/net/ipv4/neigh/lo/base_reachable_time
###"NETFILTER"###
echo 33554432 > /proc/sys/net/netfilter/nf_conntrack_max
echo 8192 > /sys/module/nf_conntrack/parameters/hashsize
echo 7200 > /proc/sys/net/netfilter/nf_conntrack_tcp_max_retrans
echo 1 > /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal
echo 15 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established
echo 15 > /proc/sys/net/netfilter/nf_conntrack_udp_timeout
echo 15 > /proc/sys/net/netfilter/nf_conntrack_udp_timeout_stream
echo 15 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_syn_recv
echo 15 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_syn_sent
echo 15 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established
echo 15 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_close
echo 15 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_close_wait
echo 15 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_fin_wait
##############################
### "DESATIVAR IPV6" ###
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/lo/disable_ipv6
##############################
